## Data Science(Continution......)
### Pandas (panel data):
- one of the datascience package.
- used as a data manupulation,data analysis, data cleaning
- #for installaton:
    - pip install pandas
- # for using:
    - import pandas as pd
### notations(datastructures in pandas):
- Series
- Data Frames

In [ ]:
# Series:
- Series is a 1d labelled array holds any data type like int,float,string
- it is collectively called as index
#syn:
pd.Series(data,index,dtype)

In [1]:
import pandas as pd
pd.__version__

'0.24.2'

In [2]:
import pandas as pd
st="hello"
pd.Series(st)

0    hello
dtype: object

In [3]:
import pandas as pd
st="hello"
pd.series(st)

AttributeError: module 'pandas' has no attribute 'series'

In [4]:
s=input().split()
pd.Series(s)

python online workshop


0      python
1      online
2    workshop
dtype: object

In [5]:
li=[123,'abc',78.90,'2.5']
pd.Series(li)

0     123
1     abc
2    78.9
3     2.5
dtype: object

In [6]:
d={'course':'python','org':'apssdc','branch':'all'}
pd.Series(d)

course    python
org       apssdc
branch       all
dtype: object

In [7]:
s={23,23,465,'abc'}  #set not supported in panda Series
pd.Series(s)

TypeError: 'set' type is unordered

In [9]:
t=(12,34,12,5,45)
pd.Series(t)

0    12
1    34
2    12
3     5
4    45
dtype: int64

In [10]:
t=(12,34,12,5,45)
pd.Series(t,index=['one','two','three','four','five'])

one      12
two      34
three    12
four      5
five     45
dtype: int64

In [11]:
t=(12,34,12,5,45)
pd.Series(t,index=['one','two','three','four'])

ValueError: Length of passed values is 5, index implies 4

In [31]:
import numpy as np
import pandas as pd
a=np.arange(4,10) #4,5,6,7,8,9
pd.Series(a,dtype="float")

0    4.0
1    5.0
2    6.0
3    7.0
4    8.0
5    9.0
dtype: float64

In [16]:
r=np.random.randint(2,20,8)
pd.Series(r)

0    13
1     5
2    11
3    12
4    18
5    12
6    15
7    19
dtype: int32

In [ ]:
#syn:
slicing----->(start,end+1,step+1)

In [23]:
print(r[2:7])
print(r[0:])
print(r[:4])
print(r[0:5:2])
print(r[::-1])

[11 12 18 12 15]
[13  5 11 12 18 12 15 19]
[13  5 11 12]
[13 11 18]
[19 15 12 18 12 11  5 13]


In [22]:
n=int(input("enter a number:")) #8
l={i:i**2 for i in range(1,n)}  #1,2,3,4,5,6,7
o=pd.Series(l)
print(o)
print(type(o))

enter a number:8
1     1
2     4
3     9
4    16
5    25
6    36
7    49
dtype: int64
<class 'pandas.core.series.Series'>


In [24]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('20-9-2020','22-9-2020'))
a

2020-09-20    1
2020-09-21    2
2020-09-22    3
Freq: D, dtype: int64

In [26]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('20-9-2020','23-10-2020'))
a

ValueError: Length of passed values is 3, index implies 34

In [29]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('02-09-2020','04-09-2020'))
a

ValueError: Length of passed values is 3, index implies 61

In [30]:
import pandas as pd
a=pd.Series([1,2,3],index=('02-09-2020','03-09-2020','04-09-2020'))
a

02-09-2020    1
03-09-2020    2
04-09-2020    3
dtype: int64

In [ ]:
# DataFrame (default table formate)
- 2d labeled array
- data analysis
# syn:
pd.DataFrame(data,columns)

In [32]:
import pandas as pd
n=input("enter a string:").split()
pd.DataFrame(n)

enter a string:python hello everyone


0
0    python
1     hello
2  everyone

In [33]:
import pandas as pd
d=[['pavani',10],['ambika',20],['vanitha',30]]
a=pd.DataFrame(d)
a

0   1
0   pavani  10
1   ambika  20
2  vanitha  30

In [34]:
import pandas as pd
d=[['pavani',10],['ambika',20],['vanitha',30]]
a=pd.DataFrame(d,columns=['Name','Age'])
a

Name  Age
0   pavani   10
1   ambika   20
2  vanitha   30

In [36]:
a={'python':22,'java':20,'c++':23}
pd.DataFrame(a)

ValueError: If using all scalar values, you must pass an index

In [37]:
a={'python':22,'java':20,'c++':23}
b={'python':25,'java':22,'c++':21}
c=pd.Series(a)   #in series keys treated as index
d=pd.Series(b)
print(c,'\n''\n',d)

python    22
java      20
c++       23
dtype: int64 

 python    25
java      22
c++       21
dtype: int64


In [38]:
final={'mid1':c,'mid2':d}  #in dataframes keys treated as columns
pd.DataFrame(final)

mid1  mid2
python    22    25
java      20    22
c++       23    21

In [40]:
d=pd.DataFrame({'name':['pavani','ambika'],'age':[23,25],'occupation':['trainer','trainer']})
d

name  age occupation
0  pavani   23    trainer
1  ambika   25    trainer

In [43]:
d={'name':'pavani','age':23,'occupation':'trainer'}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [42]:
d={'name':'pavani','age':23,'occupation':'trainer'}
pd.DataFrame(d,index=[1])

name  age occupation
1  pavani   23    trainer

In [41]:
d={23,4,5,'abc','23'} # dataframe supports set
pd.DataFrame(d)

0
0    4
1    5
2  abc
3   23
4   23

In [44]:
t=(24,56,78,23,78)
pd.DataFrame(t)

0
0  24
1  56
2  78
3  23
4  78

In [54]:
import pandas as pd
d1={'Name':'pavani','Age':23,'Occupation':'trainer'}
d2={'Name':'ambika','Age':24,'Occupation':'trainer'}
d3={'Name':'vanitha','Age':22}
s=pd.DataFrame([d1,d2,d3],index=['one','two','three'])
s

Age     Name Occupation
one     23   pavani    trainer
two     24   ambika    trainer
three   22  vanitha        NaN

In [55]:
s.loc['two']  #index name

Age                24
Name           ambika
Occupation    trainer
Name: two, dtype: object

In [56]:
s.iloc[0] #index value

Age                23
Name           pavani
Occupation    trainer
Name: one, dtype: object

In [57]:
s['Age']=23
s

Age     Name Occupation
one     23   pavani    trainer
two     23   ambika    trainer
three   23  vanitha        NaN

In [59]:
s.T

one      two    three
Age              23       23       23
Name         pavani   ambika  vanitha
Occupation  trainer  trainer      NaN

In [60]:
s.T.loc['Name']

one       pavani
two       ambika
three    vanitha
Name: Name, dtype: object

In [61]:
s.T.iloc[2]

one      trainer
two      trainer
three        NaN
Name: Occupation, dtype: object

In [63]:
s

Age     Name Occupation
one     23   pavani    trainer
two     23   ambika    trainer
three   23  vanitha        NaN

In [66]:
s.drop('three')

Age    Name Occupation
one   23  pavani    trainer
two   23  ambika    trainer

In [67]:
s

Age     Name Occupation
one     23   pavani    trainer
two     23   ambika    trainer
three   23  vanitha        NaN

In [69]:
d1=pd.DataFrame({'name':['pavani','ambika','vanitha'],'age':[23,25,22],'occupation':['trainer','trainer','trainer']},index=[1,2,3])
d1

name  age occupation
1   pavani   23    trainer
2   ambika   25    trainer
3  vanitha   22    trainer

In [78]:
d2=pd.DataFrame({'name1':['hello','hi','evryone'],'age1':[23,25,22]},index=[1,4,3])
d2

name1  age1
1    hello    23
4       hi    25
3  evryone    22

In [79]:
d1.join(d2)

name  age occupation    name1  age1
1   pavani   23    trainer    hello  23.0
2   ambika   25    trainer      NaN   NaN
3  vanitha   22    trainer  evryone  22.0

In [80]:
d2.join(d1)

name1  age1     name   age occupation
1    hello    23   pavani  23.0    trainer
4       hi    25      NaN   NaN        NaN
3  evryone    22  vanitha  22.0    trainer