## Data Science:
- organising,processing,analysing the huge amount of data.
- involves different disciplines like mathematical and statistical modelling.
- extracting data from the source
- apply data visulization
- in python we have nearly 20 python libraries for datascience
- # top 3:
    - Numpy
    - Pandas
    - Matplotlib

In [ ]:
# Numpy:
- numpy is a python library
- numerical python
- fundamental package for scientific computing in python
- it is used to create multidimensional arrays for fast operations.
- numpy have a fixed size of arrays used to store a collection of elements.

In [ ]:
#installtion (numpy):
- pip install numpy (windows)
- sudo apt-get install python3 numpy
#for using numpy:
- import numpy as np

In [1]:
import numpy as np
np.__version__

'1.16.4'

In [9]:
# 1 dimensional array
import numpy as np
dim1=np.array([2,5,1,6,4,6])
print(dim1)
print(type(dim1))
dim1

[2 5 1 6 4 6]
<class 'numpy.ndarray'>


array([2, 5, 1, 6, 4, 6])

In [10]:
# 2 dimensional array
import numpy as np
dim2=np.array([[2,5,1],[6,4,6]])   #[[a],[b]]
print(dim2)
print(type(dim2))
dim2

[[2 5 1]
 [6 4 6]]
<class 'numpy.ndarray'>


array([[2, 5, 1],
       [6, 4, 6]])

In [11]:
import numpy as np
li=[2,1,4,'z']
a1=np.array(li)
print(a1)
a1

['2' '1' '4' 'z']


array(['2', '1', '4', 'z'], dtype='<U11')

In [12]:
np.array([3.14,4,2,9])

array([3.14, 4.  , 2.  , 9.  ])

In [13]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [15]:
np.array([1., 2., 3., 4.],dtype="int")

array([1, 2, 3, 4])

In [16]:
# multi dimensional:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
[2,4,6]----># 2--->range(2,5)---->2,3,4
            #4---->range(4,7)---->4,5,6
            #6----->range(6,9)--->6,7,8

In [18]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [19]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
import numpy as np
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros((3,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.ones((5),dtype="float")

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.linspace(0,5) #default 50

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [5]:
np.linspace(0,5,10,retstep=True)

(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]),
 0.5555555555555556)

In [6]:
np.linspace(0,5,100,retstep=True)

(array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
        0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
        1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
        1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
        2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
        2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
        3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
        3.53535354, 3.58585859, 3.63636364, 3.68

In [4]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [12]:
np.random.randint(1,50)

40

In [16]:
np.random.randint(1,50,size=(4,4))

array([[22, 18, 33, 38],
       [24, 31, 16, 14],
       [43,  1, 41,  6],
       [40, 33,  3, 24]])

In [97]:
import numpy as np
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [22]:
# with mean 0 and standarddeviation 1
np.random.normal(0,1,size=(3,3))

array([[-1.07518981, -1.6373903 , -0.15120616],
       [ 1.5488357 ,  0.05082339,  0.67053255],
       [-1.20181783,  0.56637178,  0.22404984]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
x1=np.arange(9).reshape((3,3))
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
x2=np.arange(9).reshape((2,4))   # 0 1 2 3 
x2                               # 4 5 6 7

ValueError: cannot reshape array of size 9 into shape (2,4)

In [31]:
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
2**x1

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [33]:
d=np.array([1,2,3,6])
np.diag(d)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 6]])

In [35]:
d=np.array([1,2,3,6]*3)
d

array([1, 2, 3, 6, 1, 2, 3, 6, 1, 2, 3, 6])

In [37]:
d=np.repeat([1,2,3,6],3)
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 6, 6, 6])

In [38]:
x=np.arange(10000) 
x

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [40]:
x=np.arange(10000).reshape(100,100)
x

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [46]:
n1=np.arange(1,5).reshape(2,2)
n2=np.arange(5,9).reshape(2,2)
print(n1)
print(n2)
print(n1+n2)
print(n1-n2)
print(n1/n2)
print(n1*n2)
print(n1%n2)
print(n1//n2)
print(n1**n2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]
[[    1    64]
 [ 2187 65536]]


In [48]:
print(n1.dot(n2)) #matrix multiplication

[[19 22]
 [43 50]]


In [ ]:
# nd arrays
- ndim
- shape
- size
- dtype
- itemsize

In [53]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize) #returns the size in bytes of each element in array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4


In [54]:
print(a)

[[1 2 3]
 [4 5 6]]


In [55]:
a[::-1] #reverse using slicing

array([[4, 5, 6],
       [1, 2, 3]])

In [56]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [64]:
import numpy as np
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[[1 2 3]
 [4 5 6]]
6
1
21
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [67]:
print(a)
print(a.max(axis=0))  #rows
print(a.max(axis=1))  #columns

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]


In [70]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [71]:
np.absolute([-2,-1,0,1,2])

array([2, 1, 0, 1, 2])

In [75]:
x=[1,2,3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [87]:
a=np.arange(3)
b=np.arange(3) [:,np.newaxis]
print(a,b)

[0 1 2] [[0]
 [1]
 [2]]


In [88]:
a=np.array([1,2,3,4,5])
a<3

array([ True,  True, False, False, False])

In [89]:
np.sum(a<3)

2

In [94]:
a=np.array([1,28,9,6,5])
z=np.sort(a) #ascending

In [95]:
z[::-1] #decending

array([28,  9,  6,  5,  1])

In [96]:
a=np.array([[1,2,3],[4,5,6]])
print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]
